### ISSUE TITLE
Improve Environment Variable Handling for API Key

### ISSUE THREAD

**Issue by davidalami** [davidalami/VulnMapAI#1]
Refactor the code to handle the absence of the OPENAI_API_KEY environment variable more gracefully in the [Advisor ](https://github.com/davidalami/VulnMapAI/blob/main/advising/llm.py) class, maybe by adding a proper error message or by asking the user to input it manually if it's not set.

**Comment by mananchawla2005** [comment]
Hey can you assign this to me?

**Comment by davidalami** [comment]
@mananchawla2005 Of course! I've assigned it to you. Thanks for taking this on! 😊

**Comment by mananchawla2005** [comment]
Hey I can work on other issues as well but unfortunately I don't have OPENAI API KEY to test on. Is there anything I can do? @davidalami

**Comment by davidalami** [comment]
Hey @mananchawla2005 , in order to obtain the API key, one should login to the [openai website ](https://platform.openai.com/account/api-keys) and create a new secret key.
