### ISSUE TITLE
Pytest is not detecting tests when running inside Docker in CI pipeline

### ISSUE THREAD

**Issue by davidalami** [davidalami/VulnMapAI#5]
**Description:**

When running pytest inside our Docker container using the GitHub Actions workflow, it's not detecting any tests, even though tests exist in our codebase. This causes the CI pipeline to fail with an exit code 5.

**Steps to Reproduce:**
1. Trigger the GitHub Actions workflow (e.g., by pushing a commit or creating a pull request).
2. Observe the step Run Tests in the workflow.

**Expected Behavior:**
Pytest should detect and run all the tests inside the Docker container.

**Actual Behavior:**
Pytest is not detecting any tests and exits with code 5.

**Comment by georgettica** [comment]
can I assist?
please assign to me

**Comment by davidalami** [comment]
Sure, @georgettica , thanks!

**Comment by JesseStorms** [comment]
Is there a reason why you're specifically testing inside of the Docker container? You can install extra packages on GitHub Runners ([docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners)), so you don't really have to rely on containers. You also can get testing done faster considering you wouldn't have to build it every time.

Also, [you forgot to actually add the tests in the Dockerfile](https://github.com/davidalami/VulnMapAI/blob/main/build/final_image/Dockerfile), which is probably why pytest isn't working in the container.

**Comment by davidalami** [comment]
Hi @JesseStorms ,

Thanks for pointing that out! There are a few reasons we chose to test inside of a Docker container:

1. Consistency: Running tests inside a container ensures we have a consistent environment every time. This minimizes the "it works on my machine" type of issues, which can be common with different setups.
2. Reproducibility: By using Docker, anyone can pull the image and reproduce the tests locally. This can be particularly beneficial for new team members coming on board.

That being said, I do see the merit in utilizing GitHub Runners directly for efficiency. We'll evaluate the trade-offs and might consider this for future updates.

And, you're absolutely right. I missed adding the tests in the Dockerfile. I'll make that correction. Thanks for catching that!

**Comment by davidalami** [comment]
@georgettica , would you like to add copying the tests to Dockerfile and enable testing back in the CI pipeline?
