### ISSUE TITLE
Backend API Endpoint for ChatGPT

### ISSUE THREAD

**Issue by davidalami** [davidalami/VulnMapAI#9]
**Is your feature request related to a problem? Please describe.**
Currently, our report template does not allow users to interactively ask follow-up questions to ChatGPT.

**Describe the solution you'd like**
Develop an endpoint in the Flask app (e.g., /ask-chatgpt) that:

1. Receives POST requests with user queries.
2. Fetches the ChatGPT API key from environment variables.
3. Uses the API key to interact with OpenAI and retrieve the response.
4. Returns the ChatGPT response to the client.

**Describe alternatives you've considered**
An alternative is to have the frontend directly communicate with the OpenAI API. However, for security reasons, it's better to keep API interactions at the backend.

**Additional context**
N/A

**Comment by SasikaSankalana** [comment]
Would like to work on this issue. Can you assign me?

**Comment by davidalami** [comment]
@SasikaSankalana , absolutely! Assigned it to you. Thanks for taking this on!
